# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [17]:
import numpy as np
a = np.arange(10).reshape(2,5)
print('list(a):',list(a)) 
print('tolist(a):',a.tolist()) #tolist可將多層皆列印出來

b = np.arange(12).reshape(2,3,2)
print(list(b))
print(b.tolist())

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
tolist(a): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
[array([[0, 1],
       [2, 3],
       [4, 5]]), array([[ 6,  7],
       [ 8,  9],
       [10, 11]])]
[[[0, 1], [2, 3], [4, 5]], [[6, 7], [8, 9], [10, 11]]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [16]:
# 記得先 Import 正確的套件

import numpy as np
a = np.random.randint(10,size=6)        #a為擁有六個元素的隨機一維陣列#
b = np.random.randint(10,size=(3,4))    #b為擁有的隨機二維陣列，每一陣列有四個元素，共12個元素#
c = np.random.randint(10,size=(2,3,2))  #c為擁有的隨機三維陣列，陣列高2，寬2、長3，共12個元素#

print(a)
print(b)
print(c)

print(a.ndim,b.ndim,c.ndim)
print(a.shape,b.shape,c.shape)
print(a.size,b.size,c.size)
print(a.dtype,b.dtype,c.dtype) #皆以32位元整數儲存#
print(a.itemsize,b.itemsize,c.itemsize)
print(len(a),len(b),len(c))
print(type(a),type(b),type(c))

[8 3 5 2 5 8]
[[6 6 9 3]
 [7 3 8 0]
 [8 1 8 6]]
[[[3 5]
  [6 7]
  [7 8]]

 [[2 6]
  [3 7]
  [0 4]]]
1 2 3
(6,) (3, 4) (2, 3, 2)
6 12 12
int32 int32 int32
4 4 4
6 3 2
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [13]:
#簡單版(遞迴)
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in interable:
        newlist.append(tolist (obj))
    return list(newlist)
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

NameError: name 'interable' is not defined

In [12]:
#進階版
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 7, 7, 3, 1, 0]
[[4, 4, 9, 9], [2, 8, 1, 6], [1, 2, 3, 5]]
[[[5, 3], [0, 0], [2, 4]], [[6, 2], [0, 3], [5, 5]]]


In [11]:
#參考同學解答
def tolist(*iterable):
    for it in iterable:
        return it.tolist()
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 7, 7, 3, 1, 0]
[[4, 4, 9, 9], [2, 8, 1, 6], [1, 2, 3, 5]]
[[[5, 3], [0, 0], [2, 4]], [[6, 2], [0, 3], [5, 5]]]
